/**
 * Format structured review data into clean Markdown output.
 */

/**
 * Format a review object into a Markdown string.
 * @param {Object} review - Structured review data from analyzer
 * @param {Object} meta - PR metadata
 * @param {string} prUrl - Original PR URL
 * @returns {string} Formatted Markdown
 */
export function formatReview(review, meta, prUrl) {
  const lines = [];

  lines.push(`## 📋 PR Review: ${meta.title}`);
  lines.push("");
  lines.push(`> **PR:** [${meta.head} → ${meta.base}](${prUrl})  `);
  lines.push(`> **Author:** @${meta.author} | **Changes:** +${meta.additions} / -${meta.deletions} across ${meta.changedFiles} files`);
  lines.push("");

  // Summary
  lines.push("### 📝 Summary");
  lines.push("");
  lines.push(review.summary || "No summary available.");
  lines.push("");

  // Risks
  lines.push("### ⚠️ Identified Risks");
  lines.push("");
  if (review.risks && review.risks.length > 0) {
    for (const risk of review.risks) {
      lines.push(`- 🔴 ${risk}`);
    }
  } else {
    lines.push("✅ No significant risks identified.");
  }
  lines.push("");

  // Suggestions
  lines.push("### 💡 Improvement Suggestions");
  lines.push("");
  if (review.suggestions && review.suggestions.length > 0) {
    for (const suggestion of review.suggestions) {
      lines.push(`- ${suggestion}`);
    }
  } else {
    lines.push("No suggestions — the code looks solid.");
  }
  lines.push("");

  // Confidence
  const confidenceEmoji =
    review.confidence === "High" ? "🟢" :
    review.confidence === "Medium" ? "🟡" : "🔴";

  lines.push("### 📊 Confidence Score");
  lines.push("");
  lines.push(`**${confidenceEmoji} ${review.confidence}**`);
  if (review.confidence_reasoning) {
    lines.push("");
    lines.push(`_${review.confidence_reasoning}_`);
  }
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("_Generated by [claude-review](https://github.com/claude-builders-bounty/claude-builders-bounty/tree/main/claude-review) · Powered by Claude API_");

  return lines.join("\n");
}
